name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0

      - name: Build project
        run: |
          echo install dependencies
          yarn
          echo build project
          yarn build

      - name: aliyun-oss-website-action
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          folder: dist
          accessKeyId: ${{ secrets.ACCESSKEYID }}
          accessKeySecret: ${{ secrets.ACCESSKEYSECRET }}
          bucket: worldcup-guess-2022
          endpoint: oss-cn-hangzhou.aliyuncs.com
          skipSetting: true